import { Day, FestivalPlan, Stage } from "./types";
import { date } from "./utils";

export const festival: FestivalPlan = {
    [Day.thursday]: [
        {
            summary: "ALEX MOFA GANG",
            location: Stage.WildCoastStage,
            start: date(20),
            end: date(21),
        },
        {
            summary: "MILLIARDEN",
            location: Stage.WildCoastStage,
            start: date(21, 30),
            end: date(22, 30),
        },
        {
            summary: "SONDASCHULE",
            location: Stage.WildCoastStage,
            start: date(23),
            end: date(24, 15),
        },
        {
            summary: "MEGALOH",
            location: Stage.WildCoastStage,
            start: date(24, 45),
            end: date(26),
        },
    ],
    [Day.friday]: [
        {
            summary: "#HURRICANESWIMTEAM",
            location: Stage.ForestStage,
            start: date(15),
            end: date(15, 30),
        },
        {
            summary: "INHALER",
            location: Stage.RiverStage,
            start: date(15, 30),
            end: date(16),
        },
        {
            summary: "GOAT GIRL",
            location: Stage.WildCoastStage,
            start: date(15, 30),
            end: date(16, 15),
        },
        {
            summary: "THE DEAD SOUTH",
            location: Stage.ForestStage,
            start: date(16),
            end: date(16, 45),
        },
        {
            summary: "WARGASM",
            location: Stage.MountainStage,
            start: date(16),
            end: date(16, 45),
        },
        {
            summary: "GAYLE",
            location: Stage.RiverStage,
            start: date(16, 30),
            end: date(17, 15),
        },
        {
            summary: "KELVYN COLT",
            location: Stage.WildCoastStage,
            start: date(16, 45),
            end: date(17, 30),
        },
        {
            summary: "GIANT ROOKS",
            location: Stage.ForestStage,
            start: date(17, 15),
            end: date(18, 15),
        },
        {
            summary: "MILLENCOLIN",
            location: Stage.MountainStage,
            start: date(17, 15),
            end: date(18, 15),
        },
        {
            summary: "LP",
            location: Stage.RiverStage,
            start: date(18),
            end: date(19),
        },
        {
            summary: "FONTAINES D.C.",
            location: Stage.WildCoastStage,
            start: date(18, 15),
            end: date(19, 15),
        },
        {
            summary: "DERMOT KENNEDY",
            location: Stage.ForestStage,
            start: date(19),
            end: date(20),
        },
        {
            summary: "WHILE SHE SLEEPS",
            location: Stage.MountainStage,
            start: date(19),
            end: date(20),
        },
        {
            summary: "CHARLI XCX",
            location: Stage.RiverStage,
            start: date(19, 45),
            end: date(21),
        },
        {
            summary: "LOOPERS",
            location: Stage.WildCoastStage,
            start: date(19, 45),
            end: date(21, 15),
        },
        {
            summary: "THE KILLERS",
            location: Stage.ForestStage,
            start: date(20, 45),
            end: date(22),
        },
        {
            summary: "NECK DEEP",
            location: Stage.MountainStage,
            start: date(21),
            end: date(22),
        },
        {
            summary: "MATISSE & SADKO",
            location: Stage.WildCoastStage,
            start: date(21, 20),
            end: date(22, 50),
        },
        {
            summary: "SDP",
            location: Stage.RiverStage,
            start: date(21, 45),
            end: date(23, 15),
        },
        {
            summary: "ELECTRIC CALLBOY",
            location: Stage.MountainStage,
            start: date(22, 45),
            end: date(23, 45),
        },
        {
            summary: "JULIAN JORDAN",
            location: Stage.WildCoastStage,
            start: date(22, 55),
            end: date(24, 30),
        },
        {
            summary: "SEEED",
            location: Stage.ForestStage,
            start: date(23),
            end: date(24, 30),
        },
        {
            summary: "MARTIN GARRIX",
            location: Stage.RiverStage,
            start: date(24, 30),
            end: date(26),
        },
    ],
    [Day.saturday]: [
        {
            summary: "SROTTGRENZE",
            location: Stage.ForestStage,
            start: date(12),
            end: date(12, 30),
        },
        {
            summary: "PANO",
            location: Stage.MountainStage,
            start: date(12),
            end: date(12, 30),
        },
        {
            summary: "HELGEN",
            location: Stage.RiverStage,
            start: date(12, 30),
            end: date(13, 15),
        },
        {
            summary: "THE LATHUMS",
            location: Stage.WildCoastStage,
            start: date(12, 45),
            end: date(13, 15),
        },
        {
            summary: "BRUTUS",
            location: Stage.ForestStage,
            start: date(13),
            end: date(13, 45),
        },
        {
            summary: "FLASH FORWARD",
            location: Stage.MountainStage,
            start: date(13),
            end: date(13, 45),
        },
        {
            summary: "HALF MOON RUN",
            location: Stage.RiverStage,
            start: date(13, 45),
            end: date(14, 30),
        },
        {
            summary: "HOLLY HUMBERSTONE",
            location: Stage.WildCoastStage,
            start: date(13, 45),
            end: date(14, 30),
        },
        {
            summary: "NOTHING BUT THIEVES",
            location: Stage.ForestStage,
            start: date(14, 15),
            end: date(15),
        },
        {
            summary: "REIGNWOLF",
            location: Stage.MountainStage,
            start: date(14, 15),
            end: date(15, 15),
        },
        {
            summary: "PROVINZ",
            location: Stage.RiverStage,
            start: date(15),
            end: date(15, 45),
        },
        {
            summary: "KAT FRANKIE",
            location: Stage.WildCoastStage,
            start: date(15),
            end: date(15, 45),
        },
        {
            summary: "BAD RELIGION",
            location: Stage.ForestStage,
            start: date(15, 40),
            end: date(16, 25),
        },
        {
            summary: "TURBOSTAAT",
            location: Stage.MountainStage,
            start: date(15, 45),
            end: date(16, 45),
        },
        {
            summary: "JUJU",
            location: Stage.RiverStage,
            start: date(16, 15),
            end: date(17, 15),
        },
        {
            summary: "JEREMIAS",
            location: Stage.WildCoastStage,
            start: date(16, 15),
            end: date(17, 15),
        },
        {
            summary: "JUMMY EAT WORLD",
            location: Stage.ForestStage,
            start: date(17, 5),
            end: date(18, 5),
        },
        {
            summary: "JC STEWART",
            location: Stage.MountainStage,
            start: date(17, 15),
            end: date(18, 15),
        },
        {
            summary: "FOALS",
            location: Stage.RiverStage,
            start: date(18),
            end: date(19),
        },
        {
            summary: "AURORA",
            location: Stage.WildCoastStage,
            start: date(18),
            end: date(19),
        },
        {
            summary: "MANDO DIAO",
            location: Stage.ForestStage,
            start: date(18, 45),
            end: date(19, 45),
        },
        {
            summary: "FIL BO RIVA",
            location: Stage.MountainStage,
            start: date(18, 50),
            end: date(20, 5),
        },
        {
            summary: "IDLES",
            location: Stage.RiverStage,
            start: date(19, 45),
            end: date(21),
        },
        {
            summary: "OH WONDER",
            location: Stage.WildCoastStage,
            start: date(19, 45),
            end: date(21),
        },
        {
            summary: "VON WEGEN LISBETH",
            location: Stage.ForestStage,
            start: date(20, 35),
            end: date(21, 50),
        },
        {
            summary: "ANTILOPEN GANG",
            location: Stage.MountainStage,
            start: date(20, 45),
            end: date(22),
        },
        {
            summary: "K.I.Z",
            location: Stage.RiverStage,
            start: date(21, 45),
            end: date(23, 15),
        },
        {
            summary: "KOLLEKTIV TURMSTRASSE LIVE",
            location: Stage.WildCoastStage,
            start: date(21, 45),
            end: date(23, 15),
        },
        {
            summary: "DEICHKIND",
            location: Stage.ForestStage,
            start: date(22, 50),
            end: date(24, 30),
        },
        {
            summary: "KITSCHKRIEG",
            location: Stage.MountainStage,
            start: date(23),
            end: date(24, 30),
        },
        {
            summary: "THE STICKMEN PROJECT",
            location: Stage.WildCoastStage,
            start: date(23, 45),
            end: date(25, 15),
        },
        {
            summary: "TWENTY ONE PILOTS",
            location: Stage.RiverStage,
            start: date(24, 30),
            end: date(26),
        },
    ],
    [Day.sunday]: [
        {
            summary: "PRESS CLUB",
            location: Stage.MountainStage,
            start: date(12),
            end: date(12, 30),
        },
        {
            summary: "2ERSITZ",
            location: Stage.ForestStage,
            start: date(12),
            end: date(12, 30),
        },
        {
            summary: "HOT MILK",
            location: Stage.RiverStage,
            start: date(12, 30),
            end: date(13),
        },
        {
            summary: "AVRALIZE",
            location: Stage.WildCoastStage,
            start: date(12, 30),
            end: date(13),
        },
        {
            summary: "NURA",
            location: Stage.MountainStage,
            start: date(13),
            end: date(13, 45),
        },
        {
            summary: "SKINDRED",
            location: Stage.ForestStage,
            start: date(13),
            end: date(13, 45),
        },
        {
            summary: "ALICE MERTON",
            location: Stage.RiverStage,
            start: date(13, 45),
            end: date(14, 30),
        },
        {
            summary: "BLOND",
            location: Stage.WildCoastStage,
            start: date(13, 45),
            end: date(14, 30),
        },
        {
            summary: "SWISS & DIE ANDERN",
            location: Stage.ForestStage,
            start: date(14, 30),
            end: date(15, 30),
        },
        {
            summary: "BLUES PILLS",
            location: Stage.MountainStage,
            start: date(14, 30),
            end: date(15, 30),
        },
        {
            summary: "TONES AND I",
            location: Stage.RiverStage,
            start: date(15, 30),
            end: date(16, 40),
        },
        {
            summary: "SCHMYT",
            location: Stage.WildCoastStage,
            start: date(15, 30),
            end: date(16, 30),
        },
        {
            summary: "ROYAL BLOOD",
            location: Stage.ForestStage,
            start: date(16, 15),
            end: date(17, 15),
        },
        {
            summary: "FRITTENBUDE",
            location: Stage.MountainStage,
            start: date(16, 15),
            end: date(17, 15),
        },
        {
            summary: "THEES UHLMANN & BAND",
            location: Stage.RiverStage,
            start: date(17, 15),
            end: date(18, 15),
        },
        {
            summary: "MINE",
            location: Stage.WildCoastStage,
            start: date(17, 15),
            end: date(18, 15),
        },
        {
            summary: "THE HIVES",
            location: Stage.ForestStage,
            start: date(18),
            end: date(19, 15),
        },
        {
            summary: "KUMMER",
            location: Stage.MountainStage,
            start: date(18),
            end: date(19, 15),
        },
        {
            summary: "KONTRA K",
            location: Stage.RiverStage,
            start: date(19),
            end: date(20, 15),
        },
        {
            summary: "TOM GREGORY",
            location: Stage.WildCoastStage,
            start: date(19),
            end: date(20, 15),
        },
        {
            summary: "BRING ME THE HORIZON",
            location: Stage.ForestStage,
            start: date(20),
            end: date(21, 15),
        },
        {
            summary: "FERDINAND FKA LEFT BOY",
            location: Stage.MountainStage,
            start: date(20),
            end: date(21, 15),
        },
        {
            summary: "LARI LUKE",
            location: Stage.WildCoastStage,
            start: date(20, 30),
            end: date(22),
        },
        {
            summary: "RISE AGAINST",
            location: Stage.RiverStage,
            start: date(21),
            end: date(22, 30),
        },
        {
            summary: "KINGS OF LEON",
            location: Stage.ForestStage,
            start: date(22, 30),
            end: date(24),
        },
    ],
    [Day.monday]: [],
};
